server:
  port: ${PORT:8761}
spring:
  application:
    name: serviceRegistry

eureka:
  instance:
    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
