spring:
  application:
    name: PRODUCT-SERVICE

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/ecommerce}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    secure-port-enabled: ${EUREKA_SECURE_PORT_ENABLED:false}
    non-secure-port-enabled: ${EUREKA_NON_SECURE_PORT_ENABLED:true}
    secure-port: 443
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

server:
  port: ${PORT:8081}
