server:
  port: ${PORT:8083}
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/ecommerce/user/**

            - id: PRODUCT-SERVICE
              uri: lb://PRODUCT-SERVICE
              predicates:
                - Path=/ecommerce/product/**

            - id: CART-SERVICE
              uri: lb://CART-SERVICE
              predicates:
                - Path=/ecommerce/cart/**

eureka:
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    secure-port-enabled: ${EUREKA_SECURE_PORT_ENABLED:false}
    non-secure-port-enabled: ${EUREKA_NON_SECURE_PORT_ENABLED:true}
    secure-port: 443
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
