server:
  address: 0.0.0.0
  port: ${PORT:8083}
spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: ${USER_SERVICE_URL:https://ecommerce-user-ilw7.onrender.com}
              predicates:
                - Path=/ecommerce/user/**

            - id: PRODUCT-SERVICE
              uri: ${PRODUCT_SERVICE_URL:https://ecommerce-product-3k7q.onrender.com}
              predicates:
                - Path=/ecommerce/product/**

            - id: CART-SERVICE
              uri: ${CART_SERVICE_URL:https://ecommerce-cart-isg6.onrender.com}
              predicates:
                - Path=/ecommerce/cart/**

eureka:
  instance:
    hostname: ${RENDER_EXTERNAL_HOSTNAME:localhost}
    secure-port-enabled: ${EUREKA_SECURE_PORT_ENABLED:false}
    non-secure-port-enabled: ${EUREKA_NON_SECURE_PORT_ENABLED:true}
    secure-port: 443
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
